### ISSUE TITLE
Pavlovs cannot appear

### ISSUE THREAD

**Issue by mxyx0412** [SuperNewRoles/SuperNewRoles#1302]
## 発生バージョン
2.0.0.0-2.0.5.0

## 発生役職/機能
Pavlovs

## 内容
Pavlovs, even if the probability is set to 100%, cannot appear.

**Comment by ykundesu** [comment]
Thank you for your report.
This issue has already been reported.
Also, please report bugs on Discord. Please do so!
https://discord.gg/Cqfwx82ynN
